version: "2"
services:

  mock-system:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "8788:8788"
    volumes:
      - ./target:/mock-system
      - /software/fileUploadPath:/software/fileUploadPath
    environment:
      TZ: Asia/Shanghai
    container_name: mock-system
    hostname: mock-system
    image: mock-system
    #    networks:
    #      - eureka-net
    # mem_limit: 400m


  # -----------------基础环境----------------------
  mock-redis:
    image: sameersbn/redis:latest
    command: redis-server --requirepass pmit123  --appendonly yes
    ports:
      - "8765:6379"
#    volumes:
#      - ./data/redis/data:/data   # 数据目录映射
#      - ./data/redis/config:/etc/redis   # 配置文件目录映射
    restart: always
    container_name: mock-redis
    hostname: mock-redis

  #  rabbitmq:
  #    image: rabbitmq:management-alpine
  #    container_name: rabbitmq
  #    environment:
  #      - RABBITMQ_DEFAULT_USER=pmit
  #      - RABBITMQ_DEFAULT_PASS=pmit123
  #    restart: always
  #    ports:
  #      - "15672:15672"
  #      - "5672:5672"
  ##    volumes:
  ##      - ./data/rabbitmq/data:/var/lib/rabbitmq      # 数据目录映射
  ##      - ./data/rabbitmq/config:/etc/rabbitmq        # 配置文件目录映射
  ##      - ./data/rabbitmq/log:/var/log/rabbitmq       # 日志目录映射
  ##    command:
  ##      --privileged=true
  #    logging:
  #      driver: "json-file"
  #      options:
  #        max-size: "200k"
  #        max-file: "10"

  # -----------------mysql-主库----------------------
#  pmit-mysql-master:
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#      --max_allowed_packet=128M
#      --default-authentication-plugin=mysql_native_password
#    build:
#      context: ./
#      dockerfile: data/mysql/Dockerfile
#    environment:
#      MYSQL_ROOT_PASSWORD: pmoit
#      TZ: Asia/Shanghai
#    restart: always
#    container_name: pmit-mysql-master
#    image: pmit-mysql-master
#    ports:
#      - "3339:3306"
#
#  # -----------------mysql-从库----------------------
#  pmit-mysql-slave:
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#      --max_allowed_packet=128M
#      --default-authentication-plugin=mysql_native_password
#    build:
#      context: ./
#      dockerfile: db/mysql/Dockerfile
#    environment:
#      MYSQL_ROOT_PASSWORD: itsys
#      TZ: Asia/Shanghai
#    restart: always
#    container_name: pmit-mysql-slave
#    image: pmit-mysql-slave
#    ports:
#      - "3340:3306"


#networks:
#  eureka-net:
#    driver: "host"
